### ISSUE TITLE
Dependencies not Found

### ISSUE THREAD

**Issue by sundasfatema** [zeeshaanahmad/url-shortener#1]
Hi, 
I was trying to build the application and was unable to setup the build environment because of Java JDK issues. There is a lack of documentation regarding the dependency requirements and packages/versions for CENTOS/Ubuntu environments. Kindly document them in the repository.

**Comment by zeeshaanahmad** [comment]
Please follow the build.gradle file for the package versions. It is based on Java 8. If you look at the api.Dockerfile, you can see it uses openjdk version 8 as base image.
